version: 2
updates:
  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'

  # Node modules
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'

  # IaC Go modules
  - package-ecosystem: 'gomod'
    directories:
      - 'environment/deploy/'
      - 'install/deploy/'
      - 'webserver/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'

  # Webserver Dockerfiles
  - package-ecosystem: 'docker'
    directory: 'webserver/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'
