# Build stage
FROM golang:1.22.1 AS builder

ENV CGO_ENABLED=0
ENV GIN_MODE=release

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /go/bin/romeo-iac ./cmd/romeo-iac/main.go



# Prod stage
FROM pulumi/pulumi-go:3.117.0
RUN pulumi login --local && \
    pulumi plugin install resource kubernetes 4.12.0 && \
    pulumi plugin install resource random 4.16.2
COPY --from=builder /go/bin/romeo-iac /romeo-iac
ENTRYPOINT [ "/romeo-iac" ]
