name: 'Romeo Environment'
author: 'ctfer-io'
description: 'Deploy a Romeo environment from an Action'
branding:
  icon: 'pie-chart'
  color: 'blue'

inputs:
  kubeconfig:
    description: 'The kubeconfig to use for deploying a Romeo environment'
    required: true
  tag:
    description: 'The Romeo webserver docker tag to use'
    required: true
    default: 'latest'
  claim-name:
    description: 'If specified, turns on Romeo''s coverage export in the given PersistenVolumeClaim name'
    required: false

outputs:
  port:
    description: 'The port to reach out the Romeo webserver'
  claim-name:
    description: 'The PersistentVolumeClaim name for binaries to mount in order to write coverage data'
  namespace:
    description: 'The namespace in which Romeo has been deployed. Reuse it to target the PersistentVolumeClaim corresponding to the claim-name'

runs:
  using: node20
  main: ../dist/environment.js
  post: ../dist/environment.js
