name: 'Romeo Environment'
author: 'ctfer-io'
description: 'Deploy a Romeo environment from an Action'
branding:
  icon: 'pie-chart'
  color: 'blue'

inputs:
  stack-name:
    description: 'The Pulumi stack name. Usefull when deploying multiple Romeo environments within the same context.'
    default: 'env'
  kubeconfig:
    description: 'The kubeconfig to use for deploying a Romeo environment'
    required: true
  namespace:
    description: 'The namespace in which to deploy, in case the kubeconfig has access to many. If not defined, will create one.'
  harden:
    description: 'Whether to harden the namespace or not. Deny all traffic, deny inter-namespace communications, then grant DNS resolution, grant internet communications, and grant access to Romeo webserver. If a namespace is defined, only grant access to Romeo webserver.'
    default: 'false'
  tag:
    description: 'The Romeo webserver docker tag to use'
    default: 'latest'
  storage-class-name:
    description: 'The StorageClass name for the PersistenVolumeClaim.'
    default: 'standard'
  storage-size:
    description: 'The storage size.'
    default: '50M'
  claim-name:
    description: 'If specified, turns on Romeo''s coverage export in the given PersistenVolumeClaim name. This should only be used by CTFer.io to test Romeo itself.'
  registry:
    description: 'An optional OCI registry to download romeo images from.'
  pvc-access-mode:
    description: 'The PVC access mode to use.'

outputs:
  port:
    description: 'The port to reach out the Romeo webserver API, as exposed by the Kubernetes cluster.'
  claim-name:
    description: 'The PersistentVolumeClaim name for binaries to mount in order to write coverage data.'
  namespace:
    description: 'The namespace in which Romeo has been deployed. Reuse it to target the PersistentVolumeClaim corresponding to the claim-name.'

runs:
  using: node20
  main: ../dist/environment.js
  post: ../dist/environment.js
