name: env
runtime: go
description: Deploy a Romeo environment
config:
  kubeconfig:
    type: string
    secret: true
    description: 'The kubeconfig to use for deploying a Romeo environment (either the content or path).'
  namespace:
    type: string
    description: 'The namespace in which to deploy, in case the kubeconfig has access to many.'
  harden:
    type: boolean
    description: 'Whether to harden the namespace or not. Deny all traffic, deny inter-namespace communications, then grant DNS resolution, grant internet communications, and grant access to Romeo webserver. If a namespace is defined, only grant access to Romeo webserver.'
    default: false
  tag:
    type: string
    description: 'The Romeo webserver docker tag to use.'
    default: 'latest'
  storage-class-name:
    type: string
    description: 'The StorageClassName for the PersistenVolumeClaim.'
    default: 'standard'
  storage-size:
    type: string
    description: 'The storage size.'
    default: '50M'
  registry:
    type: string
    description: 'An optional OCI registry to download romeo images from.'
  claim-name:
    type: string
    description: 'If specified, turns on Romeo''s coverage export in the given PersistenVolumeClaim name.'
  pvc-access-mode:
    type: string
    description: 'The PVC access mode to use.'
    default: 'ReadWriteMany'

author: CTFer.io
license: Apache-2.0
website: https://ctfer.io/docs/romeo
