# Build stage
FROM golang:1.23.2 AS builder

ENV CGO_ENABLED=0

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /go/bin/romeo main.go



# Prod stage
FROM golang:1.23.2
COPY --from=builder /go/bin/romeo /romeo
ENTRYPOINT [ "/romeo" ]
