apiVersion: v1
kind: Config
clusters:
- name: cluster
  cluster:
    certificate-authority-data: {{ .CaCrt }}
    server: {{ .Server }}
contexts:
- name: romeo-context
  context:
    cluster: cluster
    namespace: {{ .Namespace }}
    user: romeo-user
current-context: romeo-context
users:
- name: romeo-user
  user:
    token: {{ .Token }}
