name: install
runtime: go
description: The Kubernetes IaC to install Romeo.
config:
  kubeconfig:
    type: string
    secret: true
    description: 'The kubeconfig to use for deploying a Romeo environment (either the content or path).'
  namespace:
    type: string
    description: 'The namespace to install Romeo into. May be randomly generated, as long as it fits Kubernetes naming specification. If not specified, will create one one the fly'
  api-server:
    type: string
    description: 'The Kubernetes api-server URL to pipe into the generated kubeconfig. Is inferred from `kubeconfig` whenever possible. Example: "https://cp.my-k8s.lan:6443"'

author: CTFer.io
license: Apache-2.0
website: https://ctfer.io/docs/romeo
