name: 'Romeo Download'
author: 'ctfer-io'
description: 'Download the Romeo coverages from an environment, after running your tests'
branding:
  icon: 'bar-chart-2'
  color: 'green'

inputs:
  server:
    description: 'Server URL to reach out the Romeo environment.'
    required: true
  strategy:
    description: |
      The strategy to download and write coverages.
      Enum contains:
      - "raw" for coverfile and covdata files in a directory
      - "coverfile" (default) for a single coverage file
    default: coverfile
  coverfile:
    description: 'The file to output coverages into.'
    default: out.cov

outputs:
  path:
    description: 'The file containing the coverages.'

runs:
  using: node20
  main: ../dist/download.js
