name: Integration tests

on:
  push:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'webserver/go.mod'

      - name: Set up Docker registry
        run: |
          docker network create kind || true
          docker run -d --network kind --name registry -p 5000:5000 registry:2
      - name: Write config file
        run: |
          cat <<EOF > kind-config.yaml
          apiVersion: kind.x-k8s.io/v1alpha4
          kind: Cluster
          containerdConfigPatches:
          - |
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
              endpoint = ["http://registry:5000"]
          
          kubeadmConfigPatches:
          - |
            kind: ClusterConfiguration
            apiServer:
              extraArgs:
                "service-node-port-range": "30000-30005"
          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 80
              hostPort: 80
            - containerPort: 30000
              hostPort: 30000
            - containerPort: 30001
              hostPort: 30001
            - containerPort: 30002
              hostPort: 30002
            - containerPort: 30003
              hostPort: 30003
            - containerPort: 30004
              hostPort: 30004
            - containerPort: 30005
              hostPort: 30005
          EOF
      - name: Set up Kind cluster
        uses: helm/kind-action@v1.7.0
        with:
          version: v0.20.0
          config: kind-config.yaml
          cluster_name: kind
        env:
          KIND_EXPERIMENTAL_DOCKER_NETWORK: kind

      - name: Export server URL
        id: server
        run: |
          echo "server=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' kind-control-plane)" >> "$GITHUB_OUTPUT"

      - name: Build and push Romeo webserver
        run: |
          cd webserver
          docker build \
              -t localhost:5000/ctferio/romeo:${{ github.sha }} .
          docker push localhost:5000/ctferio/romeo:${{ github.sha }}

      - name: Install Pulumi
        uses: pulumi/actions@v4
      - name: Prepare environment
        run: |
          pulumi login --local
          kubectl create ns romeo-in-ci

      - name: Romeo environment
        id: env
        uses: ctfer-io/romeo/environment@939d724d971219fe434333aeaa1ef6ea049ea053
        with:
          private-registry: localhost:5000
          kubeconfig: ~/.kube/config
          namespace: romeo-in-ci
          storage-class-name: standard
          tag: ${{ github.sha }}

      - name: Romeo environment under test
        id: env-test
        uses: ctfer-io/romeo/environment@939d724d971219fe434333aeaa1ef6ea049ea053
        with:
          private-registry: localhost:5000
          kubeconfig: ~/.kube/config
          storage-class-name: standard
          claim-name: ${{ steps.env.outputs.claim-name }}
          tag: ${{ github.sha }}

      - name: Stimulate
        run: |
          curl -v "${{ steps.server.outputs.server }}:${{ steps.env.outputs.port }}/api/v1/coverout"

      - name: Get raw results
        run: |
          curl -v "${{ steps.server.outputs.server }}:${{ steps.env-test.outputs.port }}/api/v1/coverout"
